name: "Dep jobs example"

on: ['push']

jobs:
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
     - name: Build
       run: echo "Build is completed" 
  Build:
    runs-on: ubuntu-latest
    steps: 
     - name: Test
       run: echo "Test is completed"

  

